name: Close Pull Request

on:
  workflow_dispatch:
  #pull_request_target:
    #types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We do not accept PRs as this is part of a internal project. If you have any questions, please feel free to contact us."
